// <auto-generated />
namespace Task4.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PurchaseMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PurchaseMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202102031754068_PurchaseMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
