// <auto-generated />
namespace Task5.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DatabaseMigrationv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabaseMigrationv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103011530554_DatabaseMigration-v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
